# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:20
from __future__ import unicode_literals

import apps.accounts.models.upload_paths
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(editable=False, max_length=150, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Last active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='doctor_role', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('photo', versatileimagefield.fields.VersatileImageField(blank=True, max_length=300, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.accounts.models.upload_paths.doctor_photo_path, verbose_name='Profile Picture')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('degree', models.CharField(blank=True, max_length=20, verbose_name='Doctoral degree')),
                ('units_of_length', models.CharField(choices=[('cm', 'Centimeter'), ('in', 'Inch')], default='in', max_length=2, verbose_name='Units of length')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='patient_role', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', versatileimagefield.fields.VersatileImageField(blank=True, max_length=300, null=True, storage=storages.backends.s3boto.S3BotoStorage(bucket='skiniq-ir4y-dev'), upload_to=apps.accounts.models.upload_paths.patient_photo_path, verbose_name='Profile Picture')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('sex', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True, verbose_name='Sex')),
                ('race', models.SmallIntegerField(blank=True, choices=[(1, 'American Indian/Alaska Native'), (2, 'Asian'), (3, 'Black/African American'), (4, 'Hispanic/Latino'), (5, 'Native Hawaiian/Pacific Islander'), (6, 'White')], null=True, verbose_name='Race')),
                ('mrn', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Medical Record Number')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.Doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
