# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='units_of_length',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('in', 'Inch')], default='in', max_length=2, verbose_name='Units of length'),
        ),
    ]
