# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 05:06
from __future__ import unicode_literals

import apps.accounts.models.upload_paths
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='tmp/images/default_profile.jpeg', max_length=300, null=True, upload_to=apps.accounts.models.upload_paths.doctor_photo_path, verbose_name='Profile Picture'),
        ),
    ]
