# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 08:49
from __future__ import unicode_literals

import apps.accounts.models.upload_paths
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_can_see_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('date_expired', models.DateTimeField(blank=True, verbose_name='Valid until')),
                ('signature', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.accounts.models.upload_paths.patient_consent_signature_path, verbose_name='Signature')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='accounts.Patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Patient consent',
                'verbose_name_plural': 'Patient consents',
                'ordering': ('-date_expired',),
            },
        ),
    ]
