# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 05:54
from __future__ import unicode_literals

import apps.accounts.models.upload_paths
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorToPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField(verbose_name='Encrypted key for patient data')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor', verbose_name='Doctor')),
            ],
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user_ptr',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.TextField(default='', verbose_name='Encrypted first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.TextField(default='', verbose_name='Encrypted last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='mrn_hash',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Hash of Medical Record Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.TextField(blank=True, null=True, verbose_name='Encrypted date of birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.TextField(blank=True, null=True, verbose_name='Encrypted Medical Record Number'),
        ),
        migrations.AddField(
            model_name='doctortopatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='patients', through='accounts.DoctorToPatient', to='accounts.Doctor'),
        ),
    ]
