# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 05:24
from __future__ import unicode_literals

import apps.accounts.models.upload_paths
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_encrypt_patient_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('doctor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Doctor')),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='private_key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='public_key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='my_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='accounts.Coordinator'),
        ),
    ]
