# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 10:04
from __future__ import unicode_literals

import apps.accounts.models.upload_paths
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_coordinator_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='coordinator',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_coordinator', to='accounts.Site'),
        ),
    ]
