# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 10:05
from __future__ import unicode_literals

import apps.accounts.models.upload_paths
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_coordinator_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='doctor_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coordinator_role', serialize=False, to='accounts.Doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn_hash',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Medical Record Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=300, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.accounts.models.upload_paths.patient_photo_path, verbose_name='Profile Picture'),
        ),
    ]
