# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170919_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('site_coordinator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='accounts.Coordinator')),
            ],
        ),
    ]
