# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='approved_by_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
