# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_site_join_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitejoinrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
