sudo: required

services:
  - docker

before_script:
- export BUILD_IMAGE=skin-api
- docker build -t $BUILD_IMAGE .
- docker-compose -f docker-compose.test.yml up -d db
- docker-compose -f docker-compose.test.yml run --rm wait_for
- docker-compose -f docker-compose.test.yml run --rm server sh -c 'coverage run ./manage.py test && coverage report'
script:
- ./run_tests.sh

after_script:
- docker-compose -f docker-compose.test.yml down

branches:
  only:
  - master
