version: '2'

services:
  server:
    image: $DOCKER_IMAGE_BUILD
    ports:
    - 8000:8000
    links:
    - db
    - redis
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
      RUN_TESTS: "True"
      IS_CI: "True"
    volumes:
    - ./reports:/app/user/reports/unit

  wait_for:
    image: jwilder/dockerize
    command: dockerize -wait tcp://db:5432 -timeout 60s
