---

version: '2'

services:
  db:
    image: postgres:9.4-alpine
    ports:
    - 5432

  redis:
    image: redis:3-alpine

  server:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    depends_on:
    - db
    - redis
    ports:
    - 8000:8000
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
      DEBUG: "True"

  celery:
    build: .
    command: celery -A skiniq worker -B -l info
    depends_on:
    - db
    - redis
    environment:
      DEBUG: "True"
      DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
      BROKER_URL: 'redis://redis'
      C_FORCE_ROOT: "True"
