# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 03:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moleimage',
            options={'ordering': ('-date_created',), 'verbose_name': 'Mole image', 'verbose_name_plural': 'Mole images'},
        ),
        migrations.AddField(
            model_name='moleimage',
            name='biopsy_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Biopsy data'),
        ),
    ]
