# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:22
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def forwards_func(apps, schema_editor):
    call_command('initialize_anatomical_sites')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('moles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
