# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:22
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify
from mptt import register


def forwards_func(apps, schema_editor):
    AnatomicalSite = apps.get_model("moles", "AnatomicalSite")
    register(AnatomicalSite)

    removed_anatomical_sites = [
        'Face',
        'Occipital scalp',
    ]
    added_anatomical_sites = [
        'Hair',
        'Forehead',
        'Temple',
        'Ear',
        'Ear lobe',
        'Ear helix',
        'Eyebrow',
        'Eyelash',
        'Eye',
        'Nose',
        'Nostril',
        'Jaw',
        'Chin',
        'Lip',
        'Mouth',
        'Cheek',
    ]

    head_anatomical_site = AnatomicalSite.objects.get(name='Head')

    for site in AnatomicalSite.objects.filter(
            name__in=removed_anatomical_sites):
        site.patientanatomicalsite_set.update(
            anatomical_site=head_anatomical_site)
        site.delete()

    for site_name in added_anatomical_sites:
        AnatomicalSite.objects.get_or_create(
            name=site_name,
            slug=slugify(site_name),
            parent=head_anatomical_site)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('moles', '0002_setup-anatomical-site'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
