# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moles', '0002_setup-anatomical-site'),
    ]

    operations = [
        migrations.AddField(
            model_name='moleimage',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Photo is approved by coordinator'),
        ),
    ]
