# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moles', '0003_moleimage_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='moleimage',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age when photo was taken'),
        ),
    ]
