# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moles', '0005_update_anatomical_sites'),
        ('moles', '0004_moleimage_age'),
    ]

    operations = [
    ]
