# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 04:30
from __future__ import unicode_literals

import apps.moles.models.upload_paths
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20171030_0837'),
        ('moles', '0006_merge_20170915_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.moles.models.upload_paths.study_consent_docs_path, verbose_name='Document file')),
            ],
            options={
                'verbose_name': 'Consent doc',
                'verbose_name_plural': 'Consent docs',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('consent_docs', models.ManyToManyField(blank=True, related_name='studies', to='moles.ConsentDoc')),
                ('doctors', models.ManyToManyField(blank=True, related_name='studies', to='accounts.Doctor')),
            ],
            options={
                'verbose_name': 'Study',
                'verbose_name_plural': 'Studies',
            },
        ),
        migrations.CreateModel(
            name='StudyToPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient', verbose_name='Patient')),
                ('patient_consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.PatientConsent')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moles.Study', verbose_name='Study')),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='studies', through='moles.StudyToPatient', to='accounts.Patient'),
        ),
    ]
