# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-20 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moles', '0008_studyinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentdoc',
            name='original_filename',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
