# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_participant'),
        ('moles', '0010_moleimage_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='accounts.Coordinator'),
        ),
    ]
