# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-14 04:19
from __future__ import unicode_literals

import apps.moles.models.upload_paths
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moles', '0011_study_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentdoc',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.moles.models.upload_paths.study_consent_docs_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg', 'pdf', 'doc', 'docx', 'odt', 'html', 'htm', 'rtf'])], verbose_name='Document file'),
        ),
    ]
