# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-04 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_participant'),
        ('moles', '0012_auto_20180614_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyinvitation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient', verbose_name='Patient'),
        ),
    ]
