# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-18 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moles', '0013_consentdoc_is_default_consent'),
        ('moles', '0013_studyinvitation_patient'),
    ]

    operations = [
    ]
