# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-18 04:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
